Repository Sahamati/account-aggregator-standards, pull requests merged in 2021-05, with the labels that each got.

#17 bug: fixed whitespace typo in CIS schema
  schemas/collective_investment_schemes/cis.xsd
Labels: bug

#6 Create Code of Conduct document
  CODE_OF_CONDUCT.md
Labels: documentation

#19 Automated generation of schemas/readme
  .github/schemas-readme.template
  .github/workflows/schemas_readme.yaml
  schemas/readme.md
  utils/gh-actions/schemas-readme-updater.sh
Labels: documentation, enhancement
